"""empty message

Revision ID: 007d652d1985
Revises: 759ea525febf
Create Date: 2020-01-08 09:44:20.177349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007d652d1985'
down_revision = '759ea525febf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('viewers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'viewers')
    # ### end Alembic commands ###
