"""empty message

Revision ID: 2659ce35cb15
Revises: 007d652d1985
Create Date: 2020-01-30 10:07:48.092513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2659ce35cb15'
down_revision = '007d652d1985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'info')
    # ### end Alembic commands ###
