"""empty message

Revision ID: 759ea525febf
Revises: 926ed5522efe
Create Date: 2019-11-26 08:50:44.135240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759ea525febf'
down_revision = '926ed5522efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compendium', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_compendium_title', table_name='compendium')
    op.create_index(op.f('ix_compendium_title'), 'compendium', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compendium_title'), table_name='compendium')
    op.create_index('ix_compendium_title', 'compendium', ['title'], unique=False)
    op.alter_column('compendium', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
