"""empty message

Revision ID: 926ed5522efe
Revises: 452fcbe7c212
Create Date: 2019-11-19 10:31:07.161955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926ed5522efe'
down_revision = '452fcbe7c212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compendium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compendium_title'), 'compendium', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compendium_title'), table_name='compendium')
    op.drop_table('compendium')
    # ### end Alembic commands ###
