"""empty message

Revision ID: a481f89df303
Revises: 
Create Date: 2019-10-01 10:19:12.795324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a481f89df303'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('st_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('lore', sa.String(), nullable=True),
    sa.Column('summary', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['st_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.String(length=150), nullable=True),
    sa.Column('charType', sa.String(length=10), nullable=True),
    sa.Column('gameId', sa.Integer(), nullable=True),
    sa.Column('lore', sa.String(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('reflex', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('vitality', sa.Integer(), nullable=True),
    sa.Column('awareness', sa.Integer(), nullable=True),
    sa.Column('willpower', sa.Integer(), nullable=True),
    sa.Column('imagination', sa.Integer(), nullable=True),
    sa.Column('attunement', sa.Integer(), nullable=True),
    sa.Column('faith', sa.Integer(), nullable=True),
    sa.Column('luck', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('pointValue', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gameId'], ['games.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
