"""empty message

Revision ID: 93d19f2cce3b
Revises: 
Create Date: 2019-09-09 12:39:28.021228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d19f2cce3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_password_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_password_key', 'users', ['password'])
    # ### end Alembic commands ###
