"""empty message

Revision ID: b7feca096717
Revises: df40c3145a73
Create Date: 2019-09-26 14:25:00.859818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7feca096717'
down_revision = 'df40c3145a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('pointValue', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'pointValue')
    # ### end Alembic commands ###
