"""empty message

Revision ID: df40c3145a73
Revises: e9d5acdcf06c
Create Date: 2019-09-19 16:15:52.840712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df40c3145a73'
down_revision = 'e9d5acdcf06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('charType', sa.String(length=10), nullable=True))
    op.add_column('characters', sa.Column('gameId', sa.Integer(), nullable=True))
    op.drop_constraint('characters_game_id_fkey', 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'games', ['gameId'], ['id'])
    op.drop_column('characters', 'char_type')
    op.drop_column('characters', 'game_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('char_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key('characters_game_id_fkey', 'characters', 'games', ['game_id'], ['id'])
    op.drop_column('characters', 'gameId')
    op.drop_column('characters', 'charType')
    # ### end Alembic commands ###
